<a href="https://colab.research.google.com/github/AriefRM/R-Manipulation/blob/main/Arief_Rachman_Maulana_Coding_Exercise_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Welcome to Coding Exercise 4

### Question 1. Points = 30
### "Shifting Members of an Array"

In this question, we want to shift our array to the right. How many times? Depends on the input. 

##### Example 1:
array = [1,2,3,4,5]
steps = 3

We need to shift the array 3 steps to the right. 
- Original array = [1,2,3,4,5]
- Step 1 = [5,1,2,3,4]
- Step 2 = [4,5,1,2,3]
- Step 3 = [3,4,5,1,2]

Answer = [3,4,5,1,2]

##### Example 2:
array = [1,2,3]
steps = 5

We need to shift the array 5 steps to the right.

- Original array = [1,2,3]
- Step 1 = [3,1,2]
- Step 2 = [2,3,1]
- Step 3 = [1,2,3]
- Step 4 = [3,1,2]
- Step 5 = [2,3,1]

Answer = [2,3,1]

In [ ]:
import numpy as np 

In [ ]:
### Write your function here ###
def shift(array, steps):
  x = np.array(array)
  y = np.roll(x,steps)

  print (y)

In [ ]:
shift([1,2,3,4,5],3)

[3 4 5 1 2]


In [ ]:
shift( [1,2,3],5)

[2 3 1]


In [ ]:
## algoritma awal yang saya bikin
x = [1,2,3,4,5]
y = np.array(x)
z = np.roll(y,3)
print (z)

[3 4 5 1 2]


### Question 2. Points = 40
### "Segitiga Paskal"

We want to generate the n-th row of "Pascal's Triangle". Your function name should be ```pascal```. For those who does not know pascal triangle, watch this video: https://www.youtube.com/watch?v=1D3KsvfB8b0 and read https://www.mathsisfun.com/pascals-triangle.html 

##### Example 1:
Input = 4,

Answer = [1,4,6,4,1]

##### Example 2:
input = 3,

Answer = [1,3,3,1]



In [ ]:
### Write your solution here ###
def pascal(n):
  results = []
  for i in range(0,n):
    row = [1]
    if results:
      last_row = results[-1]
      row.extend([sum(pair) for pair in zip(last_row, last_row[1:])])
      row.append(1)
      results.append(row)
    return results

In [ ]:
pascal(2)

[[1], [1, 1]]

In [4]:
def pascal(n_rows):
    results = []
    for _ in range(n_rows):
        row = [1]
        if results:
            last_row = results[-1]
            row.extend([sum(pair) for pair in zip(last_row, last_row[1:])])
            row.append(1)
        results.append(row)
    return results

In [6]:
pascal(4)
print(pascal(4))

[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1]]


### Question 3. Points = 30

### "Maximum Distance Between 3 Points"

Given three coordinates, determine which two points are the furthest apart, and output the length of their distance. Your function should be called ```max_distance```. First coordinate is called 'A', second coordinate is called 'B', third coordinate is called 'C'. 


##### Example:
A = [1,2],
B = [10,-10],
C = [-3, 5]

- The distance between AB = 15
- The distance between BC = 19.8
- The distance between AC = 8.06

Answer = "The point A, B are furthest apart with distance 19.8"


In [2]:
### Write your solution here ###
def max_distance(A,B,C):
  distAB = ((A[0]-B[0])**2+(A[1]-B[1])**2)**.5
  distBC = ((B[0]-C[0])**2+(B[1]-C[1])**2)**.5
  distAC = ((A[0]-C[0])**2+(A[1]-C[1])**2)**.5

  ABC = (distAB,distBC,distAC)
  max_value = max(ABC)

  print ('The Distance between AB :', distAB)
  print ('The Distance between BC :', distBC)
  print ('The Distance between AC :', distAC)

  if (max_value == distAB):
    print ('The point A, B are furthest apart with distance',max_value)
  elif (max_value == distBC):
    print ('The point B, C are furthest apart with distance', max_value)
  elif (max_value == distAC):
    print ('The point A, C are furthest apart with distance', max_value)






In [15]:
max_distance([1,2],[10,-10],[-3, 5]) # Case jawaban dari pertanyaan

The Distance between AB : 15.0
The Distance between BC : 19.849433241279208
The Distance between AC : 5.0
The point B, C are furthest apart with distance 19.849433241279208


In [3]:
max_distance([3,8],[-15,-6],[4, -7]) # mencoba dengan data koordinat yang lain

The Distance between AB : 22.80350850198276
The Distance between BC : 19.026297590440446
The Distance between AC : 15.033296378372908
The point A, B are furthest apart with distance 22.80350850198276


In [ ]:
## Percobaan Algoritma yang saya buat
A = [1,2] 
B = [10,-10]
C = [-3, 5]

In [ ]:
dist = ((A[0]-B[0])**2+(A[1]-B[1])**2)**.5
print (dist)

15.0


In [2]:
a = 1
b = 5
c = 3
d = (a,b,c)
max(d)

5

In [9]:
if (d==b):
  print ('Okeh')
else :
  print ('yee')

yee
